apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fraud-api-metrics
  namespace: fraud-api
  labels:
    app: fraud-api
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: fraud-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
